# Generated by Django 5.2.1 on 2025-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da campanha', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descrição da campanha', null=True)),
                ('history', models.TextField(blank=True, help_text='História da campanha', null=True)),
            ],
        ),
    ]
