# Generated by Django 5.2.1 on 2025-06-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do evento', null=True, upload_to='events/'),
        ),
    ]
