# Generated by Django 5.2.2 on 2025-06-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_campaign_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Imagem', null=True, upload_to='')),
                ('fixed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Descrição', null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='campaign.campaign')),
            ],
        ),
    ]
