# Generated by Django 5.2.2 on 2025-06-10 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
        ('tags', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fixed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem', null=True, upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='tags.tag'),
        ),
    ]
