# Generated by Django 5.2.2 on 2025-06-10 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_fixed_alter_note_image_alter_note_tag'),
        ('tags', '0004_alter_tag_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='tags.tag'),
        ),
    ]
