# Generated by Django 5.2.2 on 2025-06-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_campaign_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do item', max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('campaign', models.ForeignKey(help_text='Campanha', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaign.campaign')),
            ],
        ),
    ]
