# Generated by Django 5.2.2 on 2025-06-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_user'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='campaign',
            field=models.ForeignKey(help_text='Campanha', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='campaign.campaign'),
        ),
    ]
