# Generated by Django 5.2.1 on 2025-05-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Imagem', null=True, upload_to='places/')),
                ('fixed', models.BooleanField(default=False, help_text='Fixo')),
                ('history', models.TextField(help_text='História', null=True)),
                ('description', models.TextField(help_text='Descrição', null=True)),
                ('campaign', models.ForeignKey(help_text='Campanha', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='campaign.campaign')),
            ],
        ),
    ]
