# Generated by Django 5.2.1 on 2025-05-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='history',
            field=models.TextField(blank=True, help_text='História', null=True),
        ),
    ]
