# Generated by Django 5.2.1 on 2025-05-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FileField(blank=True, help_text='Imagem do personagem', null=True, upload_to='characters/'),
        ),
    ]
